services:
  ######################################################
  # R
  ######################################################
  r-ver:
    image: r-package-development:4.0.0
    build:
      context: ./
      dockerfile: ./.app/docker/r/Dockerfile
      args:
        - R_REPOS='https://mran.microsoft.com/snapshot/2020-04-24'
    container_name: r-package-test-rig
    restart: always
  ######################################################
  # MLflow and Metaflow
  ######################################################
  mlflow:
    image: modelflow:4.0.0
    build:
      context: ./
      dockerfile: ./.app/docker/modelflow/Dockerfile
      args:
        - R_REPOS='https://mran.microsoft.com/snapshot/2020-04-24'
        - METAFLOW_VER='2.2.0'
        - MLFLOW_VER='1.8.0'
    container_name: modelflow
    ports:
      - 5050:80
    restart: "no"
  ####################################################
version: "3.8"
networks:
  default:
    name: ml-dev
